version: '3.8'

services:
  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    environment:
      - DEBUG=1
      - SECRET_KEY=your_secret_key
      - DB_NAME=clone
      - DB_USER=root
      - DB_PASSWORD=root_password
      - DB_HOST=db
      - DB_PORT=3306
    depends_on:
      - db  # Ensures the web service starts after the database

  db:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: clone
      MYSQL_USER: root
      MYSQL_PASSWORD: root_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql  # Persistent database storage

volumes:
  db_data:
